info:
  title: Pezastro API
  version: 1.0.0
  description:
    API for Pezastro company. Pezastro is a company that provides services
    for gardening and tree care.
tags: []
paths: {}
openapi: 3.1.0
components:
  schemas:
    Customer:
      type: object
      required:
        - name
        - id
      properties:
        name:
          type: string
          examples:
            - Pepa Vokurka
        note:
          type: string
          examples:
            - A nice fella
        id:
          type: string
          examples:
            - sd23mkm23kkmm4
      description: Customer with name and node
    Contact:
      type: object
      required:
        - id
        - name
        - customerId
      properties:
        id:
          type: string
          examples:
            - sd23mkm23kkmm4
        name:
          type: string
          examples:
            - J.K. Rowling
            - Henry Miller
        phone:
          type: integer
        examples:
          - 78232399
        email:
          type: string
        customerId:
          type: string
      description: Contact options for a customer.
    Location:
      type: object
      properties:
        id:
          type: string
        address:
          type: object
          properties:
            streetAndNumber:
              type: string
            city:
              type: string
          required:
            - streetAndNumber
            - city
        note:
          type: string
        customerId:
          type: string
      required:
        - id
        - address
        - customerId
      description: Location owned/managed by the owner. Place, where the work is done.
    LocationPartialUpdate:
      type: object
      properties:
        address:
          type: object
          properties:
            streetAndNumber:
              type: string
            city:
              type: string
          required: []
        note:
          type: string
        customerId:
          type: string
      required: []
      description:
        Data transfer object for partially updating an existing Location
        (PATCH operation).
      x-fiddle-dto-info:
        baseSchemaName: Location
    LocationCreate:
      type: object
      properties:
        address:
          type: object
          properties:
            streetAndNumber:
              type: string
            city:
              type: string
          required:
            - streetAndNumber
            - city
        note:
          type: string
        customerId:
          type: string
      required:
        - address
        - customerId
      description: Data transfer object for creating a new Location.
      x-fiddle-dto-info:
        baseSchemaName: Location
    ContactPartialUpdate:
      type: object
      properties:
        name:
          type: string
        phone:
          type: integer
        email:
          type: string
        customerId:
          type: string
      required: []
      description:
        Data transfer object for partially updating an existing Contact
        (PATCH operation).
      x-fiddle-dto-info:
        baseSchemaName: Contact
    ContactCreate:
      type: object
      properties:
        name:
          type: string
        phone:
          type: integer
        email:
          type: string
        customerId:
          type: string
      required:
        - name
        - customerId
      description: Data transfer object for creating a new Contact.
      x-fiddle-dto-info:
        baseSchemaName: Contact
    CustomerCreate:
      type: object
      properties:
        name:
          type: string
        note:
          type: string
      required:
        - name
      description: Data transfer object for creating a new Customer.
      x-fiddle-dto-info:
        baseSchemaName: Customer
    CustomerPartialUpdate:
      type: object
      properties:
        name:
          type: string
        note:
          type: string
      required: []
      description:
        Data transfer object for partially updating an existing Customer
        (PATCH operation).
      x-fiddle-dto-info:
        baseSchemaName: Customer
    Contract:
      type: object
      properties:
        id:
          type: string
        totalCost:
          type: integer
        dateOfSigning:
          type: string
        note:
          type: string
        locationId:
          type: string
      required:
        - id
        - totalCost
        - locationId
      description: Contract on a specific location.
    ContractCreate:
      type: object
      properties:
        totalCost:
          type: integer
        dateOfSigning:
          type: string
        note:
          type: string
        locationId:
          type: string
      required:
        - totalCost
        - locationId
      description: Data transfer object for creating a new Contract.
      x-fiddle-dto-info:
        baseSchemaName: Contract
    ContractPartialUpdate:
      type: object
      properties:
        totalCost:
          type: integer
        dateOfSigning:
          type: string
        note:
          type: string
        locationId:
          type: string
      required: []
      description:
        Data transfer object for partially updating an existing Contract
        (PATCH operation).
      x-fiddle-dto-info:
        baseSchemaName: Contract
    JobDescription:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        cost:
          type: string
        frequency:
          type: integer
        period:
          type: string
          enum:
            - month
            - year
        contractId:
          type: string
      required:
        - id
        - name
        - contractId
      description: Describes, what needs to be done. Part of the contract.
    JobDescriptionCreate:
      type: object
      properties:
        name:
          type: string
        cost:
          type: string
        frequency:
          type: integer
        period:
          type: string
        contractId:
          type: string
      required:
        - name
        - contractId
      description: Data transfer object for creating a new JobDescription.
      x-fiddle-dto-info:
        baseSchemaName: JobDescription
    JobDescriptionPartialUpdate:
      type: object
      properties:
        name:
          type: string
        cost:
          type: string
        frequency:
          type: integer
        period:
          type: string
        contractId:
          type: string
      required: []
      description: Data transfer object for partially updating an existing
        JobDescription (PATCH operation).
      x-fiddle-dto-info:
        baseSchemaName: JobDescription
    Job:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
        note:
          type: string
        contratctId:
          type: string
      required:
        - id
        - date
        - note
        - contratctId
      description: Every job done.
    JobCreate:
      type: object
      properties:
        date:
          type: string
        note:
          type: string
        contratctId:
          type: string
      required:
        - date
        - note
        - contratctId
      description: Data transfer object for creating a new Job.
      x-fiddle-dto-info:
        baseSchemaName: Job
    JobPartialUpdate:
      type: object
      properties:
        date:
          type: string
        note:
          type: string
        contratctId:
          type: string
      required: []
      description:
        Data transfer object for partially updating an existing Job (PATCH
        operation).
      x-fiddle-dto-info:
        baseSchemaName: Job
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        password:
          type: string
      required:
        - id
        - username
        - password
      description: ""
    UserCreate:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
      description: Data transfer object for creating a new User.
      x-fiddle-dto-info:
        baseSchemaName: User
    UserPartialUpdate:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required: []
      description:
        Data transfer object for partially updating an existing User (PATCH
        operation).
      x-fiddle-dto-info:
        baseSchemaName: User
  responses:
    Conflict:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                examples:
                  - Lorem ipsum
      description: The request could not be completed due to a conflict with the
        current state of the resource. Resolve the conflict and try again.
    NotFound:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                examples:
                  - Lorem ipsum
      description:
        The server cannot find the requested resource. The endpoint may be
        invalid or the resource may no longer exist.
    BadRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                examples:
                  - Lorem ipsum
      description:
        The server could not understand the request due to invalid syntax.
        The client should modify the request and try again.
    InternalServerErrror:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                examples:
                  - Lorem ipsum
      description:
        The server encountered an unexpected condition that prevented it
        from fulfilling the request. Report the issue to the support team if it
        persists.
  parameters: {}
